version: '3'

services:
  frontend:
    build: ./client
    restart: always
    ports: 
      - '3000:3000'
  api:
    build: ./server
    restart: always
    ports: 
      - '4444:4444'
    depends_on:
      -  mongo
   mongo:
    image: mongo
    restart: always
    environment:
     DATABASE: #
